// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Launch struct {
	FlightNumber    int     `json:"flight_number"`
	MissionName     string  `json:"mission_name"`
	LaunchYear      *string `json:"launch_year"`
	LaunchDateLocal *string `json:"launch_date_local"`
	LaunchSuccess   *bool   `json:"launch_success"`
	Rocket          *Rocket `json:"rocket"`
}

type Rocket struct {
	RocketID   string  `json:"rocket_id"`
	RocketName string  `json:"rocket_name"`
	RocketType *string `json:"rocket_type"`
}
